### ISSUE TITLE
Can't compile with MSVC 2017 when targeting x86

### ISSUE THREAD

**Issue by mwu-tow** [woboq/verdigris#30]
The README says to define `__cpp_constexpr=201304` when compiling with MSVC. However, such macro causes compilation errors with Qt headers when targeting x86.  Thiago Macieira stated that adding such definition is a mistake, so apparently this behaviour is by-design (perhaps some part of their stupid war with MSVC team) — see https://bugreports.qt.io/browse/QTBUG-67259. 

It might be worth to document the issue in README, so other people won't waste time on that. Or please put some pressure on Qt folks to consider fixing the issue.

**Comment by ogoffart** [comment]
Can you try to add `-DQT_POPCOUNT_CONSTEXPR` ?

**Comment by ogoffart** [comment]
No, ignore that comment, this will not help.

**Comment by mwu-tow** [comment]
Thank you for quick reaction and proposing the patch! 

The library is really great (I find templated Q_OBJECTs particularly useful for reducing boilerplate) , it would be too sad if such an issue blocked VS users from adoption.

**Comment by mwu-tow** [comment]
I just confirmed that the issue is fixed as of the latest Qt 5.11 beta 4. My project that uses verdigris builds fine on VS 2017.6 for both  32- and 64-bit targets. Thanks again! :-)
