### ISSUE TITLE
cannot compile with qt5.7RC and MinGW5.3

### ISSUE THREAD

**Issue by ericLemanissier** [woboq/verdigris#1]
When compiling a cpp file using verdigris, I get the following error on `W_OBJECT_IMPL(MyApp)`

> ..\Common\verdigris\src/wobjectimpl.h:753:65: error: 'QMetaObject{QMetaObject::<anonymous struct>{(& QApplication::staticMetaObject), ((const QByteArrayData*)(& w_internal::BuildStringDataHelper<std::integer_sequence<unsigned int, 0u, 1u, 2u, 3u, 4u, 5u, 6u>, std::integer_sequence<unsigned int, 0u, 1u>, std::integer_sequence<unsigned int, 0u, 6u>, std::integer_sequence<unsigned int, 6u, 1u>, MyApp::W_MetaObjectCreatorHelper>::qt_meta_stringdata.w_internal::qt_meta_stringdata_t<2, 7>::data)), ((const uint*)(& w_internal::build_int_data<std::integer_sequence<unsigned int, 7u, 0u, 0u, 14u, 0u, 14u, 0u, 14u, 0u, 14u, 0u, 14u, 4u, 0u> >::data)), MyApp::qt_static_metacall, 0u, 0u}}' is not a constant expression
>          w_internal::createMetaObject<W_MACRO_REMOVEPAREN(TYPE)>();
>                                                                  ^
> ..\Common\verdigris\src/wobjectimpl.h:756:5: note: in expansion of macro 'W_OBJECT_IMPL_COMMON'
>      W_OBJECT_IMPL_COMMON(TYPE, __VA_ARGS__) \
>      ^
> ..\Common\myapp.cpp:495:1: note: in expansion of macro 'W_OBJECT_IMPL'
>  W_OBJECT_IMPL(MyApp)
>  ^

Qt version is 5.7.0 RC and the compiler is MinGW 5.3.0
If it does not work with MinGW currently shipped with Qt on windows, then the documentation should state the minimum GCC version compatible with vertidgris

**Comment by ogoffart** [comment]
Thanks for the bug report.  Should be fixed now.
